# MDPIC Configuration
## Docs: https://github.com/skycity233/MDPIC/README.md
## Source: https://github.com/skycity233/MDPIC

github_username: malaxiaolongmao
repository_name: MLXLMblogPictures
language: en-US
hotkey: f8

